# Done to increase the memory available to Gradle.
org.gradle.jvmargs=-Xmx2G
org.gradle.parallel=true

# Mod properties
mod_version = 2.7.0.0
maven_group = rip.ysm
archives_name = openysm
enabled_platforms = fabric

# Minecraft properties
minecraft_version = 26.1.2

# Dependencies
fabric_loader_version = 0.19.2
fabric_api_version = 0.155.2+26.1.2
forge_config_api_port_version = mwAOaKnn
architectury_api_version = 20.0.12
cardinal_components_version = 8.0.0
